### ISSUE TITLE
questions about the result

### ISSUE THREAD

**Issue by februaryfang** [milaboratory/mixcr#131]
hello,
I used MiXCR for Illumina PE data from human TCR. I have two questions about the result.
1. The two analysis results were not consistent with same command lines. I followed the tutorial from url 'https://mixcr.readthedocs.io/en/latest/quickstart.html'. The command lines are like follows:

`java -jar mixcr-1.8.1/mixcr.jar align --library local --species human --loci TRA --report alignmentReport.log -OvParameters.geneFeatureToAlign=VTranscript --save-description --not-aligned-R1 fq1.unmapped --not-aligned-R2 fq2.unmapped R1.fq R2.fq alignments.vdjca`
`java -jar mixcr-1.8.1/mixcr.jar assemble --report assembleReport.log alignments.vdjca clones.clns`
`java -jar mixcr-1.8.1/mixcr.jar exportClones -f clones.clns clones.txt`

The first time, I got a lots of clonetypes and their corresponding counts. Then I lost the 'alignments.vdjca' file with some reason. So I run the same command line again. But this time I found the clonetype's count were changed. 
1. I checked the result from tutorial url 'https://mixcr.readthedocs.io/en/latest/quickstart.html#saving-links-between-initial-reads-and-clones'. The command lines are like follows:
   `java -jar mixcr-1.8.1/mixcr.jar assemble --report assembleReport2.log --index indexFile alignments.vdjca clones2.clns`
   `java -jar mixcr-1.8.1/mixcr.jar exportAlignments -cloneId indexFile -descrR1 -descrR2 alignments.vdjca alignments2.txt`
   But I got a error for option '-descrR2'. And it worked when I deleted the option '-descrR2'. I found the overlapped percent from 'alignmentReport.log' file. So, MiXCR only uses the reads from R1 instead of the reads from both R1 and R2 when the reads from R1 is not overlaped with the reads from R2, am I right?

I really need your help.
Thanks.

**Comment by PoslavskySV** [comment]
1. It is strange that running MiXCR two times you got different results. 
As I see you use `--library local`: are you sure that your local library was not changed between runs?

2. Regarding `descr2` option: I just checked and there is really a minor bug -- it will be fixed in the upcoming release.

Regarding your last question: MiXCR alway uses both R1 and R2 reads (when they contain some meaningful information), not only when reads are overlapped.

**Comment by februaryfang** [comment]
I‘m sure the local library was not changed. 
I run the same command line again. And I got a new different result for both successfully aligned reads and clonetype's count compares to before. Have you ever come to the same situation that reanalysis of same data get a different result ?

**Comment by dbolotin** [comment]
MIXCR 1.8.* must produce the same result for the same input data. Could you please provide input files and exact sequence of commands that led to this behaviour.

MiXCR aligner uses random generator to distribute initial K-mers in target sequences, and before 1.8 the generator was randomly seeded on each execution, which may led to slightly different results (few sequences from million may be differently aligned or not aligned at all from run to run), but with 1.8 release we fixed the seed of random generator, so recent versions should produce completely reproducible results.

Random distribution of seeds protects our aligner from making reproducible false-negative alignment calls in different sequences, which may led to introduction of artificial biases to results.

Anyway this "randomness" affects only very poor alignments with short alignment regions (like data with short read length and highly hypermutated antibody), and should not be the case for TR data.


Please also consider the following suggestions about commands you use:

1. If you are using IMGT reference, the `VTranscript` must be completely absent in it (please see [this](https://github.com/milaboratory/mixcr/issues/79#issuecomment-214648975) and [this](https://github.com/milaboratory/mixcr/issues/79#issuecomment-214759087) comments). There is an automatic correction of featureToAlign for such cases, which must've been triggered in this case, and neglected effect of `-OvParameters.geneFeatureToAlign=VTranscript`.

2. Don't align your data against any particular locus, try to align it against all loci, and then export only data of interest. Like this:

```
java -jar mixcr-1.8.1/mixcr.jar align --library local --species human --report alignmentReport.log --save-description --not-aligned-R1 fq1.unmapped --not-aligned-R2 fq2.unmapped R1.fq R2.fq alignments.vdjca
java -jar mixcr-1.8.1/mixcr.jar assemble --report assembleReport.log alignments.vdjca clones.clns
java -jar mixcr-1.8.1/mixcr.jar exportClones -l TRA -f clones.clns clones.TRA.txt
```

**Comment by februaryfang** [comment]
hello, dbolotin 
My input data are obtained using 5’RACE-based amplification protocols from TCR gene. I don't think my data is the reason. And it is not convenient to put my data here.
This situation just was found by accident because I want to find the origin reads linked to clonetype. Maybe this "randomness" affects very poor, but the truth is that I can't restore them now.

I also have some questions about your suggestions:
For 1. I changed my reference to the defult model with mixcr-1.8.2/mixcr.jar program. The result was also not consistent. Would you give me your test data? 

For 2. My data are from TCR gene, so I aligned them with particular loci. I tried to align them against all loci, but I got a decreasing alignment reads and clonetypes and counts. What was that mean? My previous result have lots of false positive? And your suggestion is not consistent whit your [tutorial](https://mixcr.readthedocs.io/en/latest/quickstart.html). I feel puzzled a lot.

**Comment by dbolotin** [comment]
To help you with your problem I need exact commands and exact MiXCR versions to reproduce the problem on our server.

I deposited two example sequence files:
https://files.pub.cdr3.net/dbolotin/3nmcDqPhtS7gKlliO3xxls7Nz_PPaHvc/example_R1.fastq.gz
https://files.pub.cdr3.net/dbolotin/3nmcDqPhtS7gKlliO3xxls7Nz_PPaHvc/example_R2.fastq.gz
and checked reproducibility of results.

You can check it by yourself:

```
wget https://files.pub.cdr3.net/dbolotin/3nmcDqPhtS7gKlliO3xxls7Nz_PPaHvc/example_R1.fastq.gz
wget https://files.pub.cdr3.net/dbolotin/3nmcDqPhtS7gKlliO3xxls7Nz_PPaHvc/example_R2.fastq.gz
wget https://github.com/milaboratory/mixcr/releases/download/v1.8.2/mixcr-1.8.2.zip
unzip mixcr-1.8.2.zip

./mixcr-1.8.2/mixcr -v

java -jar mixcr-1.8.2/mixcr.jar align -f --report alignment_report_rep1.log --save-description \
    --not-aligned-R1 fq1_rep1.unmapped --not-aligned-R2 fq2_rep1.unmapped \
    example_R1.fastq.gz example_R2.fastq.gz alignments_rep1.vdjca
java -jar mixcr-1.8.2/mixcr.jar assemble -f --report assemble_report_rep1.log alignments_rep1.vdjca clones_rep1.clns
java -jar mixcr-1.8.2/mixcr.jar exportClones -f clones_rep1.clns clones_rep1.txt

java -jar mixcr-1.8.2/mixcr.jar align -f --report alignment_report_rep2.log --save-description \
    --not-aligned-R1 fq1_rep2.unmapped --not-aligned-R2 fq2_rep2.unmapped \
    example_R1.fastq.gz example_R2.fastq.gz alignments_rep2.vdjca
java -jar mixcr-1.8.2/mixcr.jar assemble -f --report assemble_report_rep2.log alignments_rep2.vdjca clones_rep2.clns
java -jar mixcr-1.8.2/mixcr.jar exportClones -f clones_rep2.clns clones_rep2.txt

md5sum *.txt
```

After rigorous review of the code we found a tiny source of randomness due to the floating point arithmetics limitation (we use `float` to save memory in several places). But this does non affect any of datasets that we checked, so MiXCR produces exactly the same results (same md5sum of final txt files) from run to run.

Could you try to run MiXCR two times on your data and verify whether the results are the same or not? If results are not the same, can you please post at least something similar to the code I posted to see all parameters of **both** executions. Instead it is impossible to understand what’s going on.

Sorry, tutorial updates goes slightly behind code updates. We just started complete refactoring of docs, so they will be up-to-date and better structured soon.

Your issue with decreased amount of aligned reads after removing of `--loci ...` option can be caused by diff-loci filter, try to disable it by adding `--diff-loci` option to your `align` command line. (Better filter is already implemented in develop branch and will be released soon).

**Comment by februaryfang** [comment]
hello,
Unfortunately,  I still do not get the same results according to your above commands.
`wget https://files.pub.cdr3.net/dbolotin/3nmcDqPhtS7gKlliO3xxls7Nz_PPaHvc/example_R1.fastq.gz
wget https://files.pub.cdr3.net/dbolotin/3nmcDqPhtS7gKlliO3xxls7Nz_PPaHvc/example_R2.fastq.gz
wget https://github.com/milaboratory/mixcr/releases/download/v1.8.2/mixcr-1.8.2.zip
unzip mixcr-1.8.2.zip

./mixcr-1.8.2/mixcr -v

java -jar mixcr-1.8.2/mixcr.jar align -f --report alignment_report_rep1.log --save-description \
    --not-aligned-R1 fq1_rep1.unmapped --not-aligned-R2 fq2_rep1.unmapped \
    example_R1.fastq.gz example_R2.fastq.gz alignments_rep1.vdjca
java -jar mixcr-1.8.2/mixcr.jar assemble -f --report assemble_report_rep1.log alignments_rep1.vdjca clones_rep1.clns
java -jar mixcr-1.8.2/mixcr.jar exportClones -f clones_rep1.clns clones_rep1.txt

java -jar mixcr-1.8.2/mixcr.jar align -f --report alignment_report_rep2.log --save-description \
    --not-aligned-R1 fq1_rep2.unmapped --not-aligned-R2 fq2_rep2.unmapped \
    example_R1.fastq.gz example_R2.fastq.gz alignments_rep2.vdjca
java -jar mixcr-1.8.2/mixcr.jar assemble -f --report assemble_report_rep2.log alignments_rep2.vdjca clones_rep2.clns
java -jar mixcr-1.8.2/mixcr.jar exportClones -f clones_rep2.clns clones_rep2.txt

md5sum *.txt
`

All commands are copy from yours. The exact MiXCR version information is as follow : 
MiXCR v1.8.2 (built Mon Aug 01 03:45:51 CST 2016; rev=8d7653a; branch=hotfix/1.8.2)
Components:
MiLib v1.5-SNAPSHOT (rev=6fb25d3; branch=UNKNOWN)

The md5sum of final txt files are as follow :
c62e560fa584f4bda1759ccef5db4ad2  clones_rep1.txt
f533996ee7a9e53424917caf192d4b87  clones_rep2.txt
 
The details of 'alignment_report_rep*.log' file are as follow :
==> alignment_report_rep1.log <==
Analysis Date: Mon Sep 05 11:39:53 CST 2016
Input file(s): example_R1.fastq.gz,example_R2.fastq.gz
Output file: alignments_rep1.vdjca
Command line arguments: align -f --report alignment_report_rep1.log --save-description --not-aligned-R1 fq1_rep1.unmapped --not-aligned-R2 fq2_rep1.unmappedexample_R1.fastq.gz example_R2.fastq.gz alignments_rep1.vdjca
Total sequencing reads: 100000
Successfully aligned reads: 94710
Successfully aligned, percent: 94.71%
Alignment filtered because of different V and J loci: 0.8%
Alignment failed, no hits (not TCR/IG?): 0.03%
Alignment failed because of absence of J hits: 3.99%
Alignment failed because of low total score: 0.47%
Overlapped, percent: 3.41%
Overlapped and aligned, percent: 3.27%
Overlapped and not aligned, percent: 0.14%
======================================

==> alignment_report_rep2.log <==
Analysis Date: Mon Sep 05 11:40:40 CST 2016
Input file(s): example_R1.fastq.gz,example_R2.fastq.gz
Output file: alignments_rep2.vdjca
Command line arguments: align -f --report alignment_report_rep2.log --save-description --not-aligned-R1 fq1_rep2.unmapped --not-aligned-R2 fq2_rep2.unmappedexample_R1.fastq.gz example_R2.fastq.gz alignments_rep2.vdjca
Total sequencing reads: 100000
Successfully aligned reads: 94710
Successfully aligned, percent: 94.71%
Alignment filtered because of different V and J loci: 0.8%
Alignment failed, no hits (not TCR/IG?): 0.03%
Alignment failed because of absence of J hits: 3.99%
Alignment failed because of low total score: 0.47%
Overlapped, percent: 3.41%
Overlapped and aligned, percent: 3.27%
Overlapped and not aligned, percent: 0.14%
======================================

Maybe the alignment results are same when we look at the log file. But when I check the clones_rep*.txt files, there were three alignment scores have changed.

clones_rep1.txt:
`1	5955	0.07298330759614678	TGTGCCAGCAGTGCGGTCAGGGAAAGAGCAGCGGTGAACACTGAAGCTTTCTTT	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	TRBV6-1*00(277.6),TRBV6-6*00(255.9),TRBV6-5*00(240.3)	TRBD1*00(26),TRBD2*00(25)	TRBJ1-1*00(234.4)	TRBC1*00(0),TRBC2*00(0)	270|283|307|0|13||65.0;270|282|307|0|12||60.0;270|282|307|0|12||60.0	13|21|36|14|22|SA15T|26.0;22|27|48|29|34||25.0	20|40|68|34|54||100.0	;				    TGTGCCAGCAGTGCGGTCAGGGAAAGAGCAGCGGTGAACACTGAAGCTTTCTTT	36								CASSAVRERAAVNTEAFF		:::::::::0::13:14:::22:34:34:54:::
31	396	0.004853298036620339	TGTGCCAGCAGTTCCCCGAGGGTAGGTCAGAGAGAACAATCAGCCCCAGCATTTT	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	TRBV6-6*00(277),TRBV6-1*00(241)		TRBJ1-5*00(229)		270|290|307|0|20|SA283CST285C|72.0;270|282|307|0|12||60.0		23|42|70|36|55||95.0TGTGCCAGCAGTTCCCCGAGGGTAGGTCAGAGAGAACAATCAGCCCCAGCATTTT	36								CASSSPRVG_RENNQPQHF		:::::::::0:17:20:::::36::55:::
46	272	0.003333578449395789	TGTGCCAGCAGTCCCCTGGAGCGGGGAACTGAGCAGTTCTTC	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	TRBV28*00(333.1)    TRBD1*00(30),TRBD2*00(30)	TRBJ2-1*00(197)	TRBC1*00(0.2)	270|282|307|0|12||60.0	2|8|36|12|18||30.0;22|28|48|19|25||30.0	29|42|70|29|42||65.0	    TGTGCCAGCAGTCCCCTGGAGCGGGGAACTGAGCAGTTCTTC	36								CASSPLERGTEQFF		:::::::::0::12:12:::18:29::42:::
`

clones_rep2.txt
`1	5955	0.07298330759614678	TGTGCCAGCAGTGCGGTCAGGGAAAGAGCAGCGGTGAACACTGAAGCTTTCTTT	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	TRBV6-1*00(277.6),TRBV6-6*00(255.9),TRBV6-5*00(239.7)	TRBD1*00(26),TRBD2*00(25)	TRBJ1-1*00(234.4)	TRBC1*00(0),TRBC2*00(0)	270|283|307|0|13||65.0;270|282|307|0|12||60.0;270|282|307|0|12||60.0	13|21|36|14|22|SA15T|26.0;22|27|48|29|34||25.0	20|40|68|34|54||100.0	;				    TGTGCCAGCAGTGCGGTCAGGGAAAGAGCAGCGGTGAACACTGAAGCTTTCTTT	36								CASSAVRERAAVNTEAFF		:::::::::0::13:14:::22:34:34:54:::
31	396	0.004853298036620339	TGTGCCAGCAGTTCCCCGAGGGTAGGTCAGAGAGAACAATCAGCCCCAGCATTTT	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	TRBV6-6*00(277),TRBV6-1*00(240.6)		TRBJ1-5*00(229)		270|290|307|0|20|SA283CST285C|72.0;270|282|307|0|12||60.0		23|42|70|36|55||95.0TGTGCCAGCAGTTCCCCGAGGGTAGGTCAGAGAGAACAATCAGCCCCAGCATTTT	36								CASSSPRVG_RENNQPQHF		:::::::::0:17:20:::::36::55:::
46	272	0.003333578449395789	TGTGCCAGCAGTCCCCTGGAGCGGGGAACTGAGCAGTTCTTC	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	TRBV28*00(333.1)    TRBD1*00(30),TRBD2*00(30)	TRBJ2-1*00(197.2)	TRBC1*00(0.2)	270|282|307|0|12||60.0	2|8|36|12|18||30.0;22|28|48|19|25||30.0	29|42|70|29|42||65.0TGTGCCAGCAGTCCCCTGGAGCGGGGAACTGAGCAGTTCTTC	36								CASSPLERGTEQFF		:::::::::0::12:12:::18:29::42:::
`

And maybe and reanalysis result would be more different with a bigger data input.

**Comment by dbolotin** [comment]
Hi,

The change in alignment scoring is absolutely ok, as I mentioned in the previous post, it happens because of floating point arithmetics limitation, and source of randomness in this case is rather fundamental: because MiXCR is multithreaded the sequences in which alignments are added to clonotypes can be slightly different from run to run. For all reasonable sizees of datasets (< 1 G sequences ) the error should be negligible. We just added rounding step for this number, as nobody doesn't need this extra digits anyway.

Please check with 1.8.2 if you have any substantial changes from run to run on the sample data, or more importantly, on your datasets?

**Comment by februaryfang** [comment]
I tried the same commands above on my data. Like I was said, there were more difference with a bigger data input. Maybe the error could be negligible with a small dataset. But how can I deal with the different clonetypes from run to run?

The md5sum of final txt files are as follow :
bf1e02c6957c2ad622cbf11f19051e67  clones_rep1.txt
61ea10d846926913cdb78e66b296d383  clones_rep2.txt

The details of 'alignment_report_rep*.log' file are as follow :
==> alignment_report_rep1.log <==
Analysis Date: Mon Sep 05 17:53:20 CST 2016
Input file(s): C1_R1.fastq.gz,C1_R2.fastq.gz
Output file: alignments_rep1.vdjca
Command line arguments: align -f --report alignment_report_rep1.log --save-description --not-aligned-R1 fq1_rep1.unmapped --not-aligned-R2 fq2_rep1.unmapped C1_R1.fastq.gz C1_R2.fastq.gz alignments_rep1.vdjca
Total sequencing reads: 8406065
Successfully aligned reads: 4633880
Successfully aligned, percent: 55.13%
Alignment filtered because of different V and J loci: 3.93%
Alignment failed, no hits (not TCR/IG?): 0.91%
Alignment failed because of absence of J hits: 36.78%
Alignment failed because of low total score: 3.25%
Overlapped, percent: 8.56%
Overlapped and aligned, percent: 2.6%
Overlapped and not aligned, percent: 5.95%

==> alignment_report_rep2.log <==
Analysis Date: Mon Sep 05 21:05:24 CST 2016
Input file(s): C1_R1.fastq.gz,C1_R2.fastq.gz
Output file: alignments_rep2.vdjca
Command line arguments: align -f --report alignment_report_rep2.log --save-description --not-aligned-R1 fq1_rep2.unmapped --not-aligned-R2 fq2_rep2.unmapped C1_R1.fastq.gz C1_R2.fastq.gz alignments_rep2.vdjca
Total sequencing reads: 8406065
Successfully aligned reads: 4633587
Successfully aligned, percent: 55.12%
Alignment filtered because of different V and J loci: 3.93%
Alignment failed, no hits (not TCR/IG?): 0.91%
Alignment failed because of absence of J hits: 36.78%
Alignment failed because of low total score: 3.25%
Overlapped, percent: 8.56%
Overlapped and aligned, percent: 2.6%
Overlapped and not aligned, percent: 5.95%

The details of 'assemble_report_rep*.log' file are as follow :
==> assemble_report_rep1.log <==
Analysis Date: Mon Sep 05 18:11:04 CST 2016
Input file(s): alignments_rep1.vdjca
Output file: clones_rep1.clns
Command line arguments: assemble -f --report assemble_report_rep1.log alignments_rep1.vdjca clones_rep1.clns
Final clonotype count: 236665
Average reads per clonotype: 17.66
Total reads used in clonotypes: 4179750
Reads used in clonotypes, percent of total: 49.72%
Clonal sequences analysed, percent of total: 50.85%
Reads used as core, percent of used: 98.33%
Mapped low quality reads, percent of used: 1.67%
Reads clustered in PCR error correction, percent of used: 2.21%
Reads pre-clustered due to the similar VJC-lists, percent of used: 0%
Percent of reads dropped due to the lack of clonal sequence: 3.53%
Percent of reads dropped due to low quality: 0.1%
Percent of reads dropped due to failed mapping: 0.65%
Reads dropped with low quality clones: 0%
Clonotypes eliminated by PCR error correction: 29310
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0

==> assemble_report_rep2.log <==
Analysis Date: Mon Sep 05 21:16:40 CST 2016
Input file(s): alignments_rep2.vdjca
Output file: clones_rep2.clns
Command line arguments: assemble -f --report assemble_report_rep2.log alignments_rep2.vdjca clones_rep2.clns
Final clonotype count: 236645
Average reads per clonotype: 17.66
Total reads used in clonotypes: 4179029
Reads used in clonotypes, percent of total: 49.71%
Clonal sequences analysed, percent of total: 50.84%
Reads used as core, percent of used: 98.33%
Mapped low quality reads, percent of used: 1.67%
Reads clustered in PCR error correction, percent of used: 2.21%
Reads pre-clustered due to the similar VJC-lists, percent of used: 0%
Percent of reads dropped due to the lack of clonal sequence: 3.54%
Percent of reads dropped due to low quality: 0.1%
Percent of reads dropped due to failed mapping: 0.65%
Reads dropped with low quality clones: 0%
Clonotypes eliminated by PCR error correction: 29312
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0

I hope you can fix it in the upcoming release.

**Comment by dbolotin** [comment]
Now, with reports, it really looks like some bug. I triple checked the code, and I still can't see the way it can result in different results on the alignment stage.

Is there a way you can share your data? Of course it will be kept confidential, and will be removed right after I figure out what's going on. If yes, here is my email bolotin . dmitriy (at) gmail com .

**Comment by februaryfang** [comment]
hello ,
Previously, I tried to align my TRA data against all loci from your suggestions.Then I found lots of strange clones. The correct clone should combination of TRAV* and TRAJ*. But I also found TRGV*/TRDV*/TRBV*/IGHV* in 'All V hits' column. And even TRDD* in 'All D hits' column.

commands :
`
mixcr-1.8.2/mixcr.jar align -f --diff-loci --report alignmentReport.log --save-description alignments.vdjca 
mixcr-1.8.2/mixcr.jar assemble -f --report assemble_report.log alignments.vdjca clones.clns
mixcr-1.8.2/mixcr.jar exportClones -l TRA -f clones.clns clones.TRA.txt
`
example of result : 
184404	3	7.137667039252886E-7	TGTGCAGCACGCCGCTGGGGGTCCGGGTATGCACTCAACTTC	DCDDDDDDDDDBDDDDDB?BBBDDCDDDEDCCADCC@BB@BD	TRAV29/DV5*01(52.7),TRAV29/DV5*01(52.7),TRBV13*02(51.3),TRBV6-6*05(51.3),TRAV29/DV5*02(49.3)	TRBD2*01(25),TRDD3*01(25),TRBD1*01(25)	TRAJ41*01(260)		267|284|300|0|16|SA276CDG279|54.0;267|284|300|0|16|SA276CDG279|54.0;270|290|302|0|18|DC274DG280ST284C|52.0;270|290|302|0|18|DC274DG280ST284C|52.0;267|282|299|0|16|SA276CI278C|49.0	25|30|48|16|21||25.0;16|21|39|16|21||25.0;18|23|36|16|21||25.0	30|51|82|21|42||105.0								    TGTGCAGCACGCCGCTGGGGGTCCGGGTATGCACTCAACTTC	30								CAARRWGSGYALNF		:::::::::0:12:16:16:::21:21::42:::

java version : jdk1.8.0_73
mixcr version : mixcr-1.8.2

**Comment by februaryfang** [comment]
@dbolotin @PoslavskySV

**Comment by PoslavskySV** [comment]
Sorry for delayed reply. Option `--diff-loci` allows V and J hits be from different loci. Once you have aligned data with `--diff-loci` you can filter only e.g. TRA alignments with

`
mixcr filterAlignments --chain TRA alignments.vdjca alignments_TRA.vdjca
` 

In the recent MiXCR 2.0 option `--diff-loci` was renamed to `--allow-chimeras`.

**Comment by februaryfang** [comment]
hi,
I tried your suggestion with running commamds as follow:
`jdk1.8.0_73/bin/java -jar mixcr-1.8.2/mixcr.jar filterAlignments --loci TRA alignments.vdjca alignments.TRA.vdjca
jdk1.8.0_73/bin/java -jar mixcr-1.8.2/mixcr.jar assemble -f --report assemble_report.log alignments.TRA.vdjca clones.TRA.clns
jdk1.8.0_73/bin/java -jar mixcr-1.8.2/mixcr.jar exportClones -l TRA -f clones.TRA.clns clones.TRA.txt
`
In fact, it's not working. "clones.TRA.txt" stills has lots of strange clones.
Have you ever meet this problem before?

Best

**Comment by PoslavskySV** [comment]
Hi,

Sorry for delay. Actually this is a correct behaviour. 

By default MiXCR tries to align each read to all loci (all IG and TCR). In the case of paired end reads, MiXCR first tries to align read to V genes. If there were successful alignments with e.g. TRAV29 and TRBV1302, then MiXCR will use only TRA and TRB loci for alignment of J part. If then J part was aligned with e.g. only TRAJ41, then MiXCR will use only TRA loci for alignment with C genes.  With the option `--allow-chimeras`, MiXCR will use *all* loci for all alignments (V/J/C).

If you want to align with e.g. *only* TRB, you should use `align` with option `--chains TRB` -- this will restrict the VDJC library used by MiXCR to only TRB locus.

In general I recommend you to try recent MiXCR version (2.0) -- it has a lot of improvements that should resolve your issues.

**Comment by februaryfang** [comment]
hi,

Thank you for your advise and I think I should try MiXCR v2.0 later.

Another question to ask is about the log file of the aligment result , we found in the log file that the **Alignment failed because of absence of J hits: 43.04%** ,
 as we are using the 5'RACE sequencing stratergy the number is too high and unreasonable.Please help to explain it.

Best

**Comment by dbolotin** [comment]
Please run mixcr with `-OallowPartialAlignments=true`, export 100 top alignments and post several alignments without J gene here.

```
mixcr align -OallowPartialAlignments=true data_R1.fastq.gz data_R2.fastq.gz result.vdjca
mixcr exportAlignmentsPretty -n 100 result.vdjca
```

It would be better if you perform analysis using MiXCR 2.0.

**Comment by februaryfang** [comment]
hi  dbolotin,
I got decrease clonetypes and counts for each clonetype when I tried MiXCR 2.0 . Maybe you have changed somewhere? Or my parameter is not true? 
Follows are the alignments without J gene and commands.

`jdk1.8.0_73/bin/java -jar mixcr-1.8.2/mixcr.jar align -f --library imgt.201631-4 --species hsa -OallowPartialAlignments=true --save-description -OvParameters.geneFeatureToAlign=VTranscript --report alignmentReport.log --chains TRA fq1 fq2 alignments.vdjca 
jdk1.8.0_73/bin/java -jar mixcr-1.8.2/mixcr.jar exportAlignmentsPretty -n 100 alignments.vdjca export.txt


>>> Read id: 13

                                                                                        V>        
                                                                                    FR3><CDR3     
  Quality     42264676772676777724267774767677747777477452676754567426427662225667724675624246    
  Target0   0 CCGCAGTGGTATCAACGCAGAGTACATGGGTCCACATCACTGCGGCCCAGCCTGGTGATACAGGCCTCTACCTCTGAAGT 79   Score
TRAV27*01 220                               tccacatcactgcAgcccagcctggtgatacaggcctctacctctg     265  216.0
TRAV27*02 220                               tccacatcactgcggcccagcctggtgatacaggccActacctctg     265  216.0

                                                                                                 
               <J                   CDR3><FR4                      FR4>                          
  Quality    72222256226772264225762777774222232232645225622655622246547462464522223455244642    
  Target0 80 TAAGGGCGGATCTGAAAAGCTGGTCTTTGGAAAGGGAATGAAACTTACAGTATACCCATATATCCAGAACCCTGACCCTG 159  Score
TRAJ57*01 26   agggcggatctgaaaagctggtctttggaaagggaaCgaaactGacagtaAaccca                       81   238.0

                                                                                                
                                                                                                
Quality     57665724422446642223232624645774467774577422653422525564546723246151136664664122    
Target0 160 CCGTGTACCAGCTGAGAGACTCCGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGGCTTTCGTGTTGATCTCGGTGGT 239  Score

                                                                            
                                                                            
Quality     444464145667611511121211133133412111121112124111224123411111    
Target0 240 CGCCGTCTCATTAAAAAAAAACTTTTTCCTTATCTCCTCTGTTCTCCCTTCCTTCTCTTC 299  Score

                                                                                             
Quality   11111212221222131112221232133212222222222222222222222333233333315325242554211111   
Target1 0 AAAGAAAAAGAAGAAGAAAAAGGAGAAGAGAGAAAGAAAAGAAAGGAATAAAGAAGGAGAAGAAGGGATAAGAGATGGAC 79  Score

                                                                                               
Quality    16442224222543222554242424222222263222642254243252264242434626264653222624224226    
Target1 80 CGGAGTGAATTGAGTTCAGAGGGGGGATATTCAGATATAAGCAGTGGAATAAACGCAGAGTACATGGGTCAACATCACGG 159  Score

                                                      <J                   CDR3><FR4              
  Quality     26222263222562662747652422252225246662276667266622277777622652222277776777762777    
  Target1 160 CGGCCCAGCCTGGTGATACAGGCCTATACCTCTGAAGTTAAGGGCGGATCTGAAAAGCTGGTCTTTGGAAAGGGAATGAA 239  Score
TRAJ57*01  26                                         agggcggatctgaaaagctggtctttggaaagggaaCgaa 65   266.0

                          FR4>                                                
  Quality     622774774665222626252227777526276225562274757446644777766625    
  Target1 240 ACTGACAGTAAACCCATATATACAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTC 299  Score
TRAJ57*01  66 actgacagtaaaccca                                             81   266.0

>>> Read id: 17

                                                                                             
Quality   11111112112111121111111222113213111122222221132214222222111122222222422222112222   
Target0 0 AAAAAGGAGAAGAAAAAAGAGAAAAAGGAGAGAAAAAAAAGAAAGAGAGGAAGGAAGAGGGGAGAAGAGAAAGATGTTGG 79  Score

                                                                                               
Quality    22222654265653412324242542422222246632542256542224552422242222225652221756667646    
Target0 80 TGAACAAGGAGAAGACGGGAGAGGAGATGCGCAGGAGTGACGGGAGTTCAGACGTGTGATCTTCCGATCTAAGCAGTGGT 159  Score

                                                       <J                  CDR3><FR4              
  Quality     67777747766776767767577567777777677777777766777667765667567776777777777776676776    
  Target0 160 ATCAACGCAGAGTACATGGGGTTGAGCTTCCTATCACAGTGGAACACCGGTAACCAGTTCTATTTTGGGACAGGGACAAG 239  Score
TRAJ49*01  20                                          gaacaccggtaaccagttctattttgggacagggacaag 58   275.0

                          FR4>                                                                    
  Quality     77766766656776777567777777645677656777777676746776777776666622244622422242362424    
  Target0 240 TTTGACGGTCATTCCAAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTCTGATCGGCAGAGCGTCGTGT 319  Score
TRAJ49*01  59 tttgacggtcattcca                                                                 74   275.0

                                                                                                
Quality     22266374236267676244623233626675776415644514547257622241111223233312331221321223    
Target0 320 AGGGAAAGCGTGTAGGCTATAGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAAAATATCACTTTTGTTCCTTCTTTT 399  Score

                                                                  
Quality     11331123231112211311211212131221111211211121211111    
Target0 400 TATCTTTTCTTCCTCACTTGTTTCTCTCCTCTTTCTTTTCTCTCCTTTCT 449  Score

>>> Read id: 25

                                                                                             
Quality   42262464672676675656577776766422246777277226222564465264622242246226777462245225   
Target0 0 CAGCAGTGGTATCAACGCAGAGTACATGGGGGACTTCTGTGAGTAGGCTGACGGCAGAAGCAGATGCCTCTGTGGACAGT 79  Score

                                        <J            CDR3><FR4                      FR4>        
  Quality    67566422624465422666656742452252262252555777772222222222224224677264675755562262    
  Target0 80 TTACCAAAGACCCCAGACCCCGCCGGCAGATGACAAGATCATCTTTGGAAAAGGTTCACGCCTTCATATTCTCCCCAATC 159  Score
TRAJ30*01 27                            agatgacaagatcatctttggaaaaggGAcacgActtcatattctcccc     75   203.0

                                                                                                
Quality     43722224423224667235453627774562432245544323622223223135125232251111113152311331    
Target0 160 TCCAGAACCCTGCCCCTGCCGTGTACCAGCTGATAGACTCAGATCTGAAGACCGTCGTGTAGGGCAAGATTGTTGGCTAT 239  Score

                                                                            
Quality     323152345222314113131411131153111141311111212111111111111111    
Target0 240 AGTGTTGATCCCGGTGGTCGCCTGTTCCTTTACAACATCATTCTTTCCTTTTTATTTTCC 299  Score

                                                                                             
Quality   22111112221222122212221211122211122333222332343214242332211321133232342132342225   
Target1 0 AGAAAAAAAGGAAGAAAAGAGAAGAAAAAAAGAAAAAGAAGAAGAAGGAAAAAGAGGTGAGAGGGAGGGAAAGGAGTTAA 79  Score

                                                                                               
Quality    34242324222222263222542233234242264222334326242564424222224256524342265256276645    
Target1 80 GAAGTGTGAACTAAAGAGAGAAGCAGGGGTAACAACGCAGAGTAAATGGGGGAATTCTGTGAGTAGGCTGACGGAAGAAG 159  Score

                                                                                                
Quality     26542523222522662642225227654522227652522422452665266277652452222477777676252525    
Target1 160 AAGAAGACTGTGTGGAAAGTTTACCAAAGAGCCGAGAAAAAGACGGAAGATGAAAAGATCATATTTGGAAAAGGGACACG 239  Score

                                                                                 
    Quality     522226252222222276262227776244276222462274747457 624777766645    
    Target1 240 AATTCATATTAAACCAAATATCCAGAACCCTGACCCTGCCGTGTACCA-GCTGAGAGACTC 299  Score
TRAV26-1*01 207                     tccagCaccTtgaTcctgccCCACGcTaCgctgagagac   245  52.0
TRAV26-1*02 207                     tccagCaccTtgaTcctgccCCACGcTaCgctgagagac   245  52.0
TRAV26-1*03 207                     tccagCaccTtgaTcctgccCCACGcTaCgctgagagac   245  52.0

>>> Read id: 32

                                                                                                  
                                      FR2><CDR2                                                   
  Quality     22122212221222123212221211122212211322223222221232223222222222222223222222222222    
  Target0   0 AAGAAAAGAAGAAAGAAGAAGAAAGAGAGAGAAGAAAAAGAAAAGAGAAAAAGAAGAAAAAGAAAGAGAAAAGAAAAAGA 79   Score
TRAV40*01 139                        agagagaga                                                 147  45.0

                                                                                               
                                                                                               
Quality    22222222122222222222222222222222222222222222265425657542422426264442222225665246    
Target0 80 AAGAAAAGAAAAAAAGAAAGGAAGAAAAAGAAAAAAAGATAAATCAAGAAGAAGACGGAATACGAGATACTCCGGAGTGA 159  Score

                                                                           CDR3><FR4              
                                                                          <J                      
  Quality     22666522275525252422222224422217566677677777756776677756776657777766667765667777    
  Target0 160 CTGGAGTTCAGACGTGTGCTCTTCCGATCTAAGCAGTGGTATCAACGCAGAGTACATGGGACCTTTGGGACAGGCACTCA 239  Score
TRAJ10*01  47                                                             acctttgggacaggcactca 66   180.0

                                                                                                  
                          FR4>                                                                    
  Quality     67777765666777757675776767645676666777656676776776577776656624244252232224664626    
  Target0 240 GCTAAAAGTGGAACTCAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTCAGATCGGTAGAGCGTCGTGT 319  Score
TRAJ10*01  67 gctaaaagtggaactc                                                                 82   180.0

                                                                                                
                                                                                                
Quality     22222222224242226626224265226556526646623335677477625242671113232324343222332224    
Target0 320 AGGGAAAGCGTGTAGGCTATAGTGTAGATCTCGTTGGTCTCCGTATCATTAAAAAAAAAAATACTTCCATCTTTTTCTTC 399  Score

                                                                                                
                                                                                                
Quality     52222232223223131112132222111111122111113111312112112111312111111131211111212111    
Target0 400 TCTTCTTTCTTTTTTTTTTTTCTTTTTTTCTTCTCTACTTTTCCATCTCTCTTTTTTTTTTCTCTTTTCTCTACTTCTTT 479  Score

                             
                             
   Quality     1321113121    
   Target0 480 CTTTTCTTTC 489  Score
TRAV1-1*01 132   tttctttc 139  40.0
TRAV1-1*02 132   tttctttc 139  40.0

`

**Comment by dbolotin** [comment]
Hi februaryfang,

your data have pretty low average quality and I also see some sample preparation artefacts.

1. Quality: numbers above the sequence are taken from reads quality score values (0-4 -> 0, 5-9 -> 1, ..., 35-39 -> 7, ...). So, too many '2'-s even in relatively high quality regions indicate some problems on the sequencing step. This problem can also be due to the bias towards low quality reads in the beginning of the file (my view of this is that, such reads geometrically are somewhere on the edge of the flowcell). Try to extract some reads skipping first 1M reads, and see what they look like, maybe quality is not the problem.

2. Sample preparation artefacts. `Read 17` from your data clearly contain genomic sequence to the left of the J gene, but still was correctly spliced with C gene on the right side.
![image](https://cloud.githubusercontent.com/assets/3062854/19305854/925138c2-907b-11e6-81af-c56f16cd2ff1.png)
   This indicates low enrichment during sample preparation. This may not even be a problem for your use-case, but I suggest discussing it with wet lab folks, at least to let them know.

Here are my suggestions.
1. As you are using 5'RACE data, and have no adapter sequences inside, try to perform analysis using `rna-seq` parameters (like [here](http://mixcr.readthedocs.io/en/latest/quickstart.html#analysis-of-rna-seq-data)) this will reliably filter out all artefact alignments "not filtered on the sample preparation step".
2. Try to trim low quality tails from reads before analysis (e.g. using `Trimmomatic`).

Concerning changed performance from 1.8.2 to 2.0. More probably this change is due to the better artefact sequence filtering (several small fixes can affect this part). If you think that you lost some true-positive reads, please track exact sequences and post it here. We test each MiXCR release on a set of different typical datasets, and in our tests, extraction performance didn't change with 2.0 release.

P.S. Positions of CDR3 sequences in paired-end reads looks unusual. Did you confirm that overall library structure is what you expected? Are input R1 and R2 reads specified in the correct order (not R2 R1)?

**Comment by dbolotin** [comment]
@februaryfang, BTW, are you working in CapitalBio?

**Comment by februaryfang** [comment]
hello Dmitry Bolotin,

Thank you for your suggestions. I'm working in CapitalBio, and trying to do some job on immuine repertoireomics.
We used the 5'RACE sequencing stratergy trying to got the complete CDR region. Unfortunately, we meet the problem that alignment failed with the absence of J hits.
The right site of the J gene was still  correctly spliced with C gene as the primer are designed at the C region.
What do you mean the genomic sequence from the left of J gene of Read 17? Do you mean by DNA sequence? I can't figure it out.
I guess maybe it is a termediate product with incomplete reconstitution.

The low read quality is due to the reason that  the read lenght is 300bp pair-end ,not the absence of J hits even after triming the low quality part.

Best
February




970558734@qq.com
 
From: Dmitry Bolotin
Date: 2016-10-12 18:30
To: milaboratory/mixcr
CC: februaryfang; State change
Subject: Re: [milaboratory/mixcr] questions about the result (#131)
Hi februaryfang,
your data have pretty low average quality and I also see some sample preparation artefacts.
Quality: numbers above the sequence are taken from reads quality score values (0-4 -> 0, 5-9 -> 1, ..., 35-39 -> 7, ...). So, too many '2'-s even in relatively high quality regions indicate some problems on the sequencing step. This problem can also be due to the bias towards low quality reads in the beginning of the file (my view of this is that, such reads geometrically are somewhere on the edge of the flowcell). Try to extract some reads skipping first 1M reads, and see what they look like, maybe quality is not the problem.
Sample preparation artefacts. Read 17 from your data clearly contain genomic sequence to the left of the J gene, but still was correctly spliced with C gene on the right side.

This indicates low enrichment during sample preparation. This may not even be a problem for your use-case, but I suggest discussing it with wet lab folks, at least to let them know.
Here are my suggestions.
1. As you are using 5'RACE data, and have no adapter sequences inside, try to perform analysis using rna-seq parameters (like here) this will reliably filter out all artefact alignments "not filtered on the sample preparation step".
2. Try to trim low quality tails from reads before analysis (e.g. using Trimmomatic).
Concerning changed performance from 1.8.2 to 2.0. More probably this change is due to the better artefact sequence filtering (several small fixes can affect this part). If you think that you lost some true-positive reads, please track exact sequences and post it here. We test each MiXCR release on a set of different typical datasets, and in our tests, extraction performance didn't change with 2.0 release.
P.S. Positions of CDR3 sequences in paired-end reads looks unusual. Did you confirm that overall library structure is what you expected? Are input R1 and R2 reads specified in the correct order (not R2 R1)?
